### ISSUE TITLE
rspecを使おう

### ISSUE THREAD

**Issue by kozo002** [halenohi/memsource#2]
デフォルトだとMiniTestなんだけど、 `gem "rspec-rails"` をGemfileのtestのグループに追加してrspecを使えるようにしよう。

**手順**
1. testディレクトリを削除
2. Gemfileのtestグループに `rspec-rails` を追加
3. `bundle install`
4. `bin/rails g rspec:install`

参考
- https://github.com/rspec/rspec-rails

**Comment by take-watanabe** [comment]
rspec追加しました。
devで追加したのですが、pull reqはどこに投げればいいですか？

**Comment by kozo002** [comment]
👍
